# ======================================================================
#          Arquivo de Ambiente Conda para o Projeto Ogum
# ======================================================================
name: ogum
channels:
  - conda-forge

dependencies:
  # 1. Base do Ambiente
  - python=3.11          # versão única
  - mamba
  - pip
  - pyyaml=6.* 

  # 2. Framework de Simulação e Visualização
  - fenics-dolfinx           # suporta Python 3.11 :contentReference[oaicite:0]{index=0}
  - gmsh
  - pyvista
  - mpi4py

  # 3. Bibliotecas de Análise de Dados e ML
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - openpyxl

  # 4. Ferramentas de Desenvolvimento e Testes
  - pytest
  - pytest-cov
  - pytest-asyncio
  - ruff

  # 5. Dependências de Interface / Jupyter
  - ipywidgets           # requerido por ogum.core
  - sphinx
  - sphinx-rtd-theme
  
  # 6. Pacotes via Pip
  - pip:
      - fastapi
      - voila
      - httpx
      - pydantic<2.0
      - pydantic-settings<2.0
