[tool.ruff]
line-length = 88
exclude = [
    "IPython/*",
    "notebooks/*",
    "ogum/core.py",
    "ogum/utils.py",
    "tests/conftest.py",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["D"]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D100", "D101", "D103", "D105"]

[tool.ruff.format]

