[tool.ruff]
line-length = 88
exclude = ["ogum/ogum64.py", "ogum/ogum72.py", "ogum/ogum80.py", "ogum/fzea.py"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["D"]
pydocstyle.convention = "google"

[tool.ruff.format]

