name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

          - name: Set up Conda
            uses: conda-incubator/setup-miniconda@v3
            with:
              environment-file: environment.yml
              activate-environment: ogum
              python-version: 3.11
              auto-update-conda: true
              channels: conda-forge


      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install -y libglu1-mesa
        shell: bash -l {0}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .
        shell: bash -l {0}

      - name: Run tests with coverage
        run: pytest --cov=ogum --cov-report=xml
        shell: bash -l {0}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
