name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # ---------- Dependências ----------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff scikit-learn

      - name: Install optional FEM dependencies
        run: |
          pip install fenicsx-dolfinx mpi4py || echo "FEM deps not available, skipping"

      # ---------- Lint ----------
      - name: Ruff lint & format check
        run: |
          ruff check .
          ruff format --check .

      # ---------- Testes ----------
      - name: Run pytest
        run: |
          pytest -q --maxfail=1 --disable-warnings
