name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Instala as dependências de produção e desenvolvimento
          pip install -r requirements.txt
          # É uma boa prática ter um requirements-dev.txt, mas por agora instalamos manualmente
          pip install pytest pytest-cov ruff

      - name: Install local package 'ogum'
        run: pip install -e .

      - name: Install optional FEM dependencies
        run: |
          pip install fenicsx-dolfinx mpi4py || echo "FEM optional dependencies not available, skipping."

      - name: Lint and Format Check
        run: |
          ruff check .
          ruff format --check .

      - name: Run tests with coverage
        run: |
          pytest --cov=ogum --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
