name: Docs Pages
on:
  push:
    branches: [main]
    paths: ["docs/**", "src/**"]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          pip install -r docs/requirements.txt
          sphinx-build -b html docs docs/_build/html
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html

